# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_auto_20160229_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='text',
            field=models.TextField(),
        ),
    ]
